config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  get 'dashboard', to: 'users#dashboard', as: :dashboard
  post 'something', to: 'kombuchas#something', as: :something
  resources :kombuchas do
    resources :transactions, only: [:new, :create]
  end
  resources :transactions, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kombucha.rb
class Kombucha < ApplicationRecord
  belongs_to :user, dependent: :destroy
  # validates :name, presence: true
  # validates :flavour, presence: true
  # validates :photo, presence: true
  mount_uploader :photo, PhotoUploader
  include PgSearch
  pg_search_scope :search_by_name_flavour_description,
                  against: [:name, :flavour, :description],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :kombucha
  validates :kombucha_id, presence: true
  validates :user_id, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :shipping_address, presence: true
  validates :card_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :kombuchas
  has_many :transactions
  mount_uploader :profile_pic, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:profile_pic, :first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:profile_pic, :first_name, :last_name])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/kombuchas_controller.rb
class KombuchasController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @kombuchas = policy_scope(Kombucha)
    @kombuchas = @kombuchas.search_by_name_flavour_description(params[:query]) if params[:query]
  end

  def all_kombuchas
    @kombuchas = Kombucha.all
    authorize @kombuchas
  end

  def show
    @kombucha = Kombucha.find(params[:id])
    @transaction = Transaction.new
    @rating = params[:jsrating]
    authorize @kombucha
  end

  def new
    @kombucha = Kombucha.new
    authorize @kombucha
  end

  def create
    @kombucha = Kombucha.new(kombucha_params)
    @kombucha.user = current_user
    authorize @kombucha
    if @kombucha.save
      redirect_to kombucha_path(@kombucha)
    else
      render "new"
    end
  end

  def edit
    @kombucha = Kombucha.find(params[:id])
    authorize @kombucha
  end

  def update
    @user = current_user
    @kombucha = Kombucha.find(params[:id])
    authorize @kombucha
    if @kombucha.update(kombucha_params)
      redirect_to @kombucha, notice: 'Cha-cha Kombucha successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @kombucha = Kombucha.find(params[:id])
    authorize @kombucha
    @kombucha.destroy
    redirect_to kombucha_path(@cocktail)
  end

  # def add_rating
  #   @kombucha.rating = window.rating
  # end

  # def something
  #   @kombucha = Kombucha.find(params[:id])
  #   redirect_to
  #   if @kombucha.update(rating_params)
  #     redirect_to @kombucha, notice: 'Cha-cha Kombucha successfully updated'
  #   else
  #     redirect_back(fallback_location: root_path)
  #   end
  # end

  private

  def kombucha_params
    params.require(:kombucha).permit(:name, :price, :rating, :flavour, :photo, :description, :quantity)
  end

  def rating_params
    params.require(:kombucha).permit(:rating)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  skip_after_action :verify_authorized
  def home
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  skip_after_action :verify_authorized, only: [:show]

  def new
    @transaction = Transaction.new
    @kombucha = Kombucha.find(params[:kombucha_id])
    authorize @transaction
  end

  def create
    @user = current_user
    @kombucha = Kombucha.find(params[:kombucha_id])
    @transaction = Transaction.new(transaction_params)
    @transaction.kombucha = @kombucha
    @transaction.user = @user
    authorize @transaction
    if @transaction.save
      redirect_to transaction_path(@transaction)
    else
      render "new"
    end
  end

  def show
  end

  private

  def transaction_params
    params.require(:transaction).permit(:first_name, :last_name, :shipping_address, :card_number)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @user = current_user
    authorize @user
    @kombuchas = Kombucha.where(user: @user)
  end

  # def add_rating
  #   @kombucha = Kombucha.find(params[:id])
  # end

  #offer an edit of boocha on the card
  #capture the rating given
  #edit this on the controller



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kombuchas/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 col-md-offset-2">
      <div class="form-title">
       <h1>Edit your Kombucha</h1>
      </div>

      <div class="row justify-content-center">
        <div class="form-questions">
          <%= simple_form_for @kombucha do |f| %>
            <%= f.input :name %>
            <%= f.input :price %>
            <%= f.input :flavour %>
            <%= f.input :quantity %>
            <%= f.input :description %>
            <%= f.input :photo %>
            <%= f.button :submit, class: "btn btn-flat banner-button" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/kombuchas/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @kombucha %> |
<%= link_to 'Back', kombuchas_path %>

app/views/kombuchas/index.html.erb
<div class="banner-content">
  <div class="text-center">
    <br>
    <br>
  <%= link_to "Add a kombucha", new_kombucha_path, class: "btn btn-flat banner-button", id: "addakombucha" %>
  </div>
</div>

<div class="cards-container">
  <% @kombuchas.each do |booch| %>
    <%= link_to kombucha_path(booch) do %>
      <div class="card">
        <% if booch.quantity == 0 %>
          <%= cl_image_tag booch.photo, height: 266, width: 300, crop: :fill, class: "bw" %>
        <% else %>
          <%= cl_image_tag booch.photo, height: 266, width: 300, crop: :fill %>
        <% end %>
        <div class="card-info">
          <div>
            <h2><%= booch.name %></h2>
            <p><%= booch.flavour %></p>
            <% if booch.quantity == 0 %>
              <p>SOLD OUT</p>
            <% else %>
            <% end %>
          </div>
          <h2 class="card-pricing">£<%= booch.price %></h2>
          <% if booch.quantity == 0 %>
          <%= cl_image_tag booch.user.profile_pic, class: "avatar-bw", height: 60, width: 60, crop: :fill %>
          <% else %>
          <%= cl_image_tag booch.user.profile_pic, class: "avatar-bordered user", height: 60, width: 60, crop: :fill %>
        <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/kombuchas/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="form">
        <div class="form-title">
         <h1>Create a new kombucha</h1>
        </div>

        <div class="form-questions">
          <%= simple_form_for @kombucha do |f| %>
          <%= f.input :name %>
          <%= f.input :price %>
          <%= f.input :flavour %>
          <%= f.input :description %>
          <%= f.input :quantity %>
          <%= f.input :photo %>
          <%= f.button :submit, class: "btn btn-flat banner-button"  %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/kombuchas/show.html.erb
<div class="show-container">
  <div class="top-show-container">
    <div class="title-box">
      <h2> <%= @kombucha.name %> </h2>
      <p><%= @kombucha.flavour.capitalize %></p>
      <p> <%= @kombucha.description %> </p>
      <p>£<%= @kombucha.price %></p>
    </div>
    <div class="booch-photo">
      <%= cl_image_tag @kombucha.photo, height: 400, width: 600, crop: :fill %>
    </div>
    <div class="show-info">

      <p><%= @kombucha.rating %></p>
      <p>Brewed by <%= @kombucha.user.first_name.capitalize %></p>
      <p><%= cl_image_tag @kombucha.user.profile_pic, class: "avatar-bordered show-avatar", height: 60, width: 60, crop: :fill %></p>
    </div>
  </div>
</div>
<div class="buy-container">
  <% unless @kombucha.user == current_user %>
    <%= link_to "Buy this Kombucha!", new_kombucha_transaction_path(@kombucha), class: 'button-show' %>
    <%= simple_form_for(@kombucha, :url =>  new_kombucha_transaction_path(kombucha_id: @kombucha.id), :method => :get) do |f| %>
      <%= f.input :quantity %>
    <% end %>
  <% end %>
</div>

<br>
<br>

<div class="d-flex justify-content-around">
  <div>

  </div>

  <% if policy(@kombucha).edit? %>
    <%= link_to "Edit your Kombucha", edit_kombucha_path(@kombucha), class: "btn btn-flat banner-button" %>

  <%= link_to "Delete your Kombucha", kombucha_path(@kombucha), class: "btn btn-flat banner-button", :method => :delete %>
  <div>

  </div>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <title>Cha Cha Kombucha</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="background">
    <%= render "shared/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <div class="social-media">
  <p>Follow us on social media!</p>
  <ul class="list-inline">

      <a href="https://www.facebook.com/">
        <i class="fab fa-facebook-f"></i> </i>
      </a>
      <a href="https://www.linkedin.com/">
        <i class="fab fa-linkedin-in"></i>
      </a>
      <a href="https://www.instagram.com/">
        <i class="fab fa-instagram"></i>
        </div>
      </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.pharmaca.com/projectwellness/wp-content/uploads/2017/12/Cocktails-1050x550.jpg);">
    <h1>Ready to Cha Cha Kombucha?</h1>
    <p>Spice up your life with the best drink in the world!</p>
    <a class="btn btn-flat banner-button" href="/kombuchas">Shop Now!</a>
</div>

<div class="wrapper">
    <div class="home-card" style="background-image: url('https://cdn-image.realsimple.com/sites/default/files/styles/rs_medium_image/public/1512053072/apple-kombucha-cocktail.jpg?itok=LbNfRXxy&1512053637')">
    </div>
    <div class="home-card" style="background-image: url('https://dietitiandebbie.com/wp-content/uploads/2017/06/Rasbperry-Ginger-Kombucha-Cocktails-2.jpg')">
    </div>
    <div class="home-card" style="background-image: url('https://www.thelittleepicurean.com/wp-content/uploads/2014/05/Honey-Paloma-Cocktail-3.jpg')">
    </div>
    <div class="home-card" style="background-image: url('https://i0.wp.com/www.freutcake.com/wp-content/uploads/2018/06/Kombucha-Mojito-3.jpg?fit=1200%2C1800')">
    </div>
  </div>

<div class="container">
  <div class="kombucha-buttons-div">
    <% if current_user %>
      <%= link_to "View My Kombuchas", dashboard_path, class:"btn btn-flat banner-button" %>
    <% end %>
  </div>

  <div class="card-product">
    <img src="https://images.unsplash.com/photo-1499638673689-79a0b5115d87?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2800&q=80">
    <div class="card-product-infos">
      <h2 style="color:#E76D83; font-size: 30px;": >What is a Kombucha?</h2>
      <p style="font-size: 20px; color: black">Kombucha is a fermented drink made from sweetened tea and a specific culture known as a scoby. Scoby stands for ‘symbiotic culture of bacteria and yeasts’. The bacteria and yeasts convert the sugar into ethanol and acetic acid. The acetic acid is what gives kombucha its distinctive sour taste.</p>
    </div>
  </div>
</div>
<div class="search-form-holder" id="something">
<%= form_tag kombuchas_path, method: :get, class: "search-form" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "search-input search-field",
      placeholder: "Search"
    %>
    <%= submit_tag "Find a Booch",
    class: "btn btn-flat search-button banner-button"
    %>
<% end %>
</div>

<div class="row justify-content-center">
<button id="clickme" class="btn btn-flat banner-button">
  Thirsty? Click me!
</button>
<script>
  const button = document.querySelector('#clickme');
  const audio = new Audio('<%= asset_path "sound.mp3" %>');

  button.addEventListener('click', (e) => {
    e.target.classList.add('disabled');
    e.target.innerText = 'Cha-Cha!';
    audio.play();
  });

</script>
</div>

app/views/shared/_navbar.html.erb
  <header>
    <div class="nav-container">

      <div class="nav-left nav-item">
        <% if  current_page?('/') || current_page?('/kombuchas') %>
          <div class="search-form-holder-home">
            <%= form_tag kombuchas_path, method: :get, class: "search-form-home" do %>
              <%= text_field_tag :query, params[:query], class: "search-input-home", placeholder: "Find a Booch"%>
            <% end %>
          </div>
         <% end %>
      </div>

      <div class="nav-img nav-item">
        <img alt="logo" src=<%= asset_path("Cha-Cha-Logo-2.png") %> >
      </div>

      <div class="nav-right nav-item">
        <div class="nav-login">
          <a class="nav-link" href="/">Home</a>
          <% if !current_user.nil? %>
          <%= link_to "Logout", destroy_user_session_path, class: 'nav-link', method: :delete %>
          <% else %>
          <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
          <!-- <a class="nav-link" href="#">Login</a> -->
          <% end %>
        </div>
      </div>
    </div>
  </header>

app/views/transactions/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="form">
      <div class="form-title">
        <h1>Your Cha-Cha Kombucha checkout form</h1>
      </div>

      <div class="row justify-content-center">
      <div class="form-questions">
        <%= simple_form_for [@kombucha, @transaction] do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :shipping_address %>
        <%= f.input :card_number %>
        <%= f.button :submit, class: "btn btn-flat banner-button" %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/show.html.erb
<div class="container-after-checkout">
  <h1>Order Complete</h1>
  <p>Booch on its way <i class="fas fa-truck"></i> </p>
  <img src="https://media.giphy.com/media/2wW3ZRY6HjP9WoXwn3/giphy.gif">
  <%= link_to "Show me more Booch", kombuchas_path, class: "btn btn-flat banner-button" %>
</div>

app/views/users/dashboard.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.min.js"></script>
<div class="text-center">
  <br>
  <br>
  <h1 style="color: #393D3F;"> Welcome, <%=@user.first_name.capitalize%>!</h1>
</div>
<br>
<br>
<div class="text-center">
  <h2> Your Kombuchas </h2>
</div>
<div class="cards-container">
  <% @kombuchas.each do |booch| %>
    <%= link_to kombucha_path(booch) do %>
      <div class="card">
        <%= cl_image_tag booch.photo, height: 266, width: 300, crop: :fill %>
        <div class="card-info">
          <div>
            <h2><%= booch.name %></h2>
            <p><%= booch.flavour %></p>
            <p> <%= booch.description %> </p>
          </div>
          <h2 class="card-pricing">£<%= booch.price %></h2>
          <%= cl_image_tag booch.user.profile_pic, class: "avatar-bordered user", height: 60, width: 60, crop: :fill %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="text-center">
  <h2> Recent purchases </h2>
</div>

<div class="cards-container-trans">
  <% @user.transactions.each do |trans| %>
    <div class="card-trans">
      <%= cl_image_tag trans.kombucha.photo, height: 266, width: 300, crop: :fill %>
      <div class="card-info-trans">
        <div>
          <h2> <%=trans.kombucha.name%> </h2>
          <p> Delivered to: <%= trans.first_name %> <%= trans.last_name %></p>

        </div>
        <h2 class="card-pricing">£<%= trans.kombucha.price %></h2>
        <%= cl_image_tag trans.user.profile_pic, class: "avatar-bordered user", height: 60, width: 60, crop: :fill %>
      </div>
      <div class="slider-container">
        <div class="slider-div">
          <div class="slider-select" id="slider-<%= trans.id %>">
            <label for="range" :style="{color: getHappinessColor}">{{val}}</label>
            <input v-model="val" id="range" type="range" min=0 max=100>
            <div class="slider outer">
              <label :style="{width: `${val}%`, borderRadius: greaterThanFifty}" for="range" aria-hidden="true" class="slider inner">
                <span :style="{right: getPlacement}">{{getHappiness}}</span>
              </label>
            </div>
          </div>
        </div>
        <div class="slider-form">
          <%= simple_form_for(trans.kombucha) do |f| %>
            <%= f.input :rating, as: :hidden, input_html: { id: "slider-#{trans.id}-form"  } %>
            <%= f.button :submit, 'Rate your purchase!', class: 'btn btn-info sliderbtn' %>
          <% end %>
          </form>
        </div>
      </div>
    </div>
  <% end %>
</div>